services:
  - type: web
    name: zus-api-chatbot
    env: docker
    repo: https://github.com/EASONTAN03/zus-api-deployment
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/v1/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
